### ISSUE TITLE
Update pinned versions for flask and urllib3

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/procbuild#41]
GitHub seems to think that the older versions have security vulnerabilities. It probably doesn't matter much for procbuild, but we should still endeavor to do The Right Thing™.

**Comment by cbcunc** [comment]
@deniederhut Would you please activate this repo for requires.io? It requires an admin of the scipy-conference organization. I would like to add a requires.io badge to the README in order to get a better look at version warnings. The scipy-conference organization already has a requires.io subscription. But individual repositories need activation on requires.io to make use of it.

**Comment by deniederhut** [comment]
I'll take a look tonight

**Comment by deniederhut** [comment]
Okay I've turned it on for procbuild and scipy_proceedings. It looks like it was only activated for SciPy-2014 😂.

For the record, here are the warnings reported from GitHub:

1. Upgrade flask to version 0.12.3 or later: https://nvd.nist.gov/vuln/detail/CVE-2018-1000656
2. Upgrade urllib3 to version 1.24.2 or later: https://nvd.nist.gov/vuln/detail/CVE-2019-11324

**Comment by cbcunc** [comment]
Fixed in #49
